# Generated by Django 5.0.9 on 2026-07-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('due_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamProductivityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('tasks_total', models.PositiveIntegerField(default=0)),
                ('tasks_done', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_stats', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'team productivity stats',
                'ordering': ['-computed_at'],
            },
        ),
    ]
