import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import app.models  # noqa: E402,F401 - REGISTERS Task (AND THE READ-ONLY EXTERNAL TABLES) ON Base.metadata
from app.core.config import get_settings  # noqa: E402
from app.models.base import Base  # noqa: E402

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
# ALEMBIC RUNS SYNCHRONOUSLY (psycopg) EVEN THOUGH THE APP QUERIES VIA asyncpg AT RUNTIME
config.set_main_option(
    "sqlalchemy.url", settings.database_url.replace("postgresql://", "postgresql+psycopg://", 1)
)

# ONLY Task (app.models.base.Base) IS TARGETED - TABLES core-django OWNS ARE MAPPED
# SEPARATELY IN app.models.external AND MUST NEVER APPEAR IN AUTOGENERATED DIFFS
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
